'use strict';

module.exports = function (/* environment, appConfig */) {
  return {
    publicServices: [
      {
        PID: '1440',
        Naam: 'Hinderpremie bij openbare werken',
        Titel: 'Hinderpremie bij openbare werken',
        Inhoud:
          'Als uw onderneming hinder ondervindt van openbare werken die de toegang tot uw vestiging ernstig bemoeilijken , kunt u onder bepaalde voorwaarden een hinderpremie krijgen van de Vlaamse overheid. De hinderpremie is een forfaitair bedrag dat u krijgt om u te helpen de nodige maatregelen te treffen en als aanmoediging om te blijven ondernemen.',
        Voorwaarden:
          "Uw onderneming komt in aanmerking voor de hinderpremie als: ze op ondernemingsniveau maximaal 9 werknemers (op ondernemingsniveau, niet op niveau van de vestiging) in dienst heeft. Uitzendkrachten worden niet meegerekend de betrokken vestiging ernstige hinder ondervindt van openbare werken . Dat betekent dat aan al deze voorwaarden moet zijn voldaan: het gaat om werken waarbij een oppervlakte van meer dan 50 vierkante meter wordt opgebroken en die geheel of gedeeltelijk op hetzelfde moment worden uitgevoerd het gaat om werken die gestart zijn na 1 juli 2017 de rijweg of een of meer rijstroken worden helemaal of gedeeltelijk afgesloten de concrete planningsdatum van de werkzaamheden is bekend en de werkzaamheden duren minstens 30 opeenvolgende kalenderdagen het adres van de betrokken vestiging ligt in de hinderzone. ze activiteiten uitoefent of diensten verleent waarvoor persoonlijk en direct contact met de klanten vereist is en die dus moeilijk kunnen worden uitgeoefend op verplaatsing. Concreet gaat het om detailhandel (winkeliers), horeca en bepaalde diensten (retail). De NACE-code van de hoofdactiviteit van de onderneming moet voorkomen op de lijst van aanvaardbare NACE-codes voor de toekenning van de hinderpremie (alleen de NACE-codes 'groep 1'.) NACE is een officiele Europese lijst van activiteitsomschrijvingen die door de RSZ, de btw-administratie en de ondernemingsloketten gebruikt wordt om bedrijven in te delen in sectoren. de betrokken vestiging vaste openingstijden heeft. Het Agentschap Innoveren & Ondernemen (Vlaio) kan altijd controles uitvoeren. Als daaruit blijkt dat er onterecht een premie is uitbetaald of dat er een te hoog bedrag is uitbetaald, kan het agentschap de premie helemaal of gedeeltelijk terugvorderen. Bekijk de video over de hinderpremie. Als u door die openbare werken uw vestiging tijdelijk moet sluiten , kunt u een bijkomende sluitingspremie krijgen.",
        Procedure:
          'Als u in aanmerking komt voor de hinderpremie, dan brengt het Agentschap Innoveren & Ondernemen (Vlaio) uw onderneming daarvan nog voor de startdatum van de werkzaamheden op de hoogte. Dat gebeurt digitaal in uw e-box of per post als u uw e-box nog niet geactiveerd hebt. Meer informatie over het gebruik van de eBox voor ondernemingen vindt u op de website van VLAIO. In die kennisgevingsbrief krijgt u meer informatie over de komende werkzaamheden en over de mogelijkheid om een hinderpremie en/of bijkomende sluitingspremie aan te vragen. U dient uw premieaanvraag in via de webapplicatie . U doet dat ten laatste 60 dagen na de datum die in de aanhef van de brief vermeld staat in elk geval veer de geplande einddatum van de werkzaamheden (ook als dat minder dan 60 dagen is). Als uw aanvraagtermijn verstreken is (als u dus te laat bent met uw aanvraag), krijgt u de boodschap dat uw edossier geannuleerde is. In die gevallen kan er niets meer gedaan worden om alsnog de uitbetaling aan te vragen. De boodschap is dus: te laat is onherroepelijk te laat. Kort na de aanvraag en na controle van de gegevens door het agentschap wordt de hinderpremie automatisch uitbetaald . Als u tijdens de werken toch de deuren moet sluiten, kunt u ook de bijkomende sluitingspremie aanvragen.',
        'Wat meebrengen': '',
        Bedrag:
          'De hinderpremie bedraagt 2.000 euro . De hinderpremie en de sluitingspremie die is toegekend na 1 januari 2018, is vrijgesteld van belastingen. Uw onderneming kan de premie maximaal 1 keer per jaar en 1 keer per hinderperiode (de periode waarin de werkzaamheden plaatsvinden die ernstige hinder veroorzaken) aanvragen. Voor openbare werken die alles samen meer dan 1 jaar duren, kunt u de hinderpremie dus maar een keer krijgen. De hinderpremie is vrijgesteld van zowel personenbelasting als vennootschapsbelasting.',
        Uitzonderingen: '',
        Regelgeving:
          'Europees wettelijk kader 18/12/2013 - Verordening (EU) nr. 1407/2013 van de Commissie betreffende de toepassing van de artikelen 107 en 108 van het Verdrag betreffende de werking van de Europese Unie op de-minimissteun Vlaams wettelijk kader 15/07/2016 - Decreet houdende toekenning van een hinderpremie aan kleine ondernemingen die ernstige hinder ondervinden van openbare werken in het Vlaamse Gewest. 12/05/2017 - Besluit van de Vlaamse Regering tot uitvoering van het decreet van 15/07/2016 houdende toekenning van een hinderpremie aan kleine ondernemingen die ernstige hinder ondervinden van openbare werken in het Vlaamse Gewest.',
        'Websites / Publication URI':
          'Hinderpremie (op VLAIO.be) (https://www.vlaio.be/nl/subsidies-financiering/hinderpremie)',
        Documenten: '',
        'Bevoegde overheid': 'Vlaamse overheid',
        'Afleverende dienst': 'Vlaamse overheid',
        'Adres afleverende dienst': '',
        Type: 'Financieel voordeel',
        Doelgroep: 'Onderneming',
        'Geografische toepassingsgebied': 'Vlaamse Gewest',
        Thema: 'Economie en Werk',
        "Thema's": 'Economie en Werk',
        'Verwant product':
          'Bijkomende sluitingspremie, Afzonderlijke sluitingspremie',
        Labels:
          'hinder, hinder bij openbare werken, werkzaamheden, compensatie, vergoeding wegenwerken, verlies door wegenwerken, schade werken, nadeelcompensatie, omzetverlies, openbare werken, wegenwerken, wegwerkzaamheden, hp',
        'Geldig van': 'vr, 03/17/2017 - 09:36',
        'Geldig tot': 'ma, 12/31/2035 - 01:00',
      },
      {
        PID: '734',
        Naam: 'Vergunning voor het verstrekken van gegiste en/of sterke dranken',
        Titel:
          'Vergunning voor het verstrekken van gegiste en/of sterke dranken',
        Inhoud:
          'Alle toekomstige uitbaters van publieke inrichtingen (vaste drankslijterijen) en reizende drankslijterijen (bijvoorbeeld tapwagen, boten, treinen e) die van plan zijn gegiste en sterke dranken te schenken, moeten een drankvergunning hebben. Een drankvergunning geeft de uitbater de toestemming om gegiste dranken (dranken met een alcoholpercentage van minder dan 22e) en sterke dranken (meer dan 22e) te schenken in publieke inrichtingen als cafes, snackbars, restaurants e',
        Voorwaarden:
          'Om een vergunning te krijgen, moet u voldoen aan alle andere reglementering die van toepassing is op de uitbating van een drankgelegenheid. U moet dus: een stedenbouwkundig vergunde inrichting of een goedgekeurde reizende inrichting hebben aan de moraliteitsvoorwaarden voldoen met de brandveiligheid in orde zijn aan de wettelijke hygienevereisten voldoen indien nodig een milieuvergunning klasse 2 hebben. De drankgelegenheid moet gelegen zijn op het grondgebied van de gemeente.',
        Procedure: 'U vraagt de vergunning aan bij uw gemeente.',
        'Wat meebrengen': '',
        Bedrag: 'De vergunning is gratis.',
        Uitzonderingen: '',
        Regelgeving:
          'Wet betreffende de vergunning voor het verstrekken van sterke drank (B.S., 30 december 1983)',
        'Websites / Publication URI': '',
        Documenten: '',
        'Bevoegde overheid': 'Federale overheid',
        'Afleverende dienst': 'Lokale overheid',
        'Adres afleverende dienst': '',
        Type: 'Toelating',
        Doelgroep: 'Onderneming, Organisatie',
        'Geografische toepassingsgebied': 'Federaal',
        Thema: 'Economie en Werk',
        "Thema's": 'Economie en Werk',
        'Verwant product':
          'Hygieneattest, Moraliteitsattest, Uittreksel uit het strafregister',
        Labels: 'alcohol, drank, drankvergunning',
        'Geldig van': 'vr, 05/17/2013 - 00:00',
        'Geldig tot': 'ma, 12/31/2035 - 01:00',
      },
      {
        PID: '699',
        Naam: 'Aanmoedigingspremie',
        Titel: 'Aanmoedigingspremie',
        Inhoud:
          'Werkt u in de privesector of in de socialprofitsector en neemt u tijdskrediet of een van de thematische verloven? Dan komt u mogelijk in aanmerking voor een aanmoedigingspremie van de Vlaamse overheid. Dat is een aanvullende uitkering, boven op de onderbrekingsuitkering die u krijgt van de Rijksdienst voor Arbeidsvoorziening (RVA).',
        Voorwaarden:
          'In de privesector kunt u in 3 gevallen een aanmoedigingspremie krijgen, namelijk als u kiest voor: zorgkrediet (tijdskrediet of thematisch verlof om voor kinderen of hulpbehoevenden te zorgen) opleidingskrediet krediet in het kader van een onderneming in moeilijkheden of herstructurering. In de socialprofitsector kunt u in 5 gevallen een aanmoedigingspremie krijgen, namelijk als u kiest voor: zorgkrediet (thematisch verlof om voor kinderen of hulpbehoevenden te zorgen) opleidingskrediet landingsbaan loopbaankrediet (als u uw loopbaan voltijds onderbreekt) krediet in het kader van een onderneming in moeilijkheden of in herstructurering. Om in aanmerking te komen voor een aanmoedigingspremie, moet u altijd: al een goedkeuring van een onderbrekingsuitkering van de RVA gekregen hebben voor uw thematisch verlof of tijdskrediet. 12 maanden aaneensluitend gewerkt hebben voordat uw tijdskrediet of thematisch verlof ingaat. Lees meer over de verschillende aanmoedigingspremies .',
        Procedure:
          'Aanvragen kan op papier maar gaat sneller en vlotter online (niet voor alle aanmoedigingspremies mogelijk). Aanvraagtermijn Aanvragen voor de aanmoedigingspremie in de socialprofitsector moet u binnen 6 maanden na de start van uw tijdskrediet of thematisch verlof aanvragen. In de privesector is er geen strikte deadline, maar de premie kan maar met een terugwerkende kracht van maximaal 6 maanden worden toegekend.',
        'Wat meebrengen': '',
        Bedrag:
          'Het bedrag van de premie hangt af van de sector waarin u werkt. de specifieke vorm van onderbreking het percentage waarmee u uw werk onderbreekt het aantal uren dat u werkte in de 12 maanden voor de onderbreking. De hoogte van het premiebedrag wordt bepaald door het laagste tewerkstellingspercentage (dus het minste aantal uren) dat u werkte in de 12 maanden voor de onderbreking. De betaling gebeurt telkens omstreeks de 15de van de maand die volgt op de maand waarop de premie betrekking heeft. Als uw onderbreking op het moment van de goedkeuring al enige tijd loopt, krijgt u meteen ook de voorgaande maanden uitbetaald.',
        Uitzonderingen: '',
        Regelgeving: '',
        'Websites / Publication URI':
          'Aanmoedigingspremie (https://www.vlaanderen.be/aanmoedigingspremies)',
        Documenten: '',
        'Bevoegde overheid': 'Vlaamse overheid',
        'Afleverende dienst': 'Vlaamse overheid',
        'Adres afleverende dienst':
          'Aanmoedigingspremies\nEllipsgebouw\nKoning Albert II laan 35\n1030 Schaarbeek\n',
        Type: 'Financieel voordeel',
        Doelgroep: 'Burger, Onderneming, Organisatie',
        'Geografische toepassingsgebied':
          'Brusselse Hoofdstedelijke Gewest, Vlaamse Gewest',
        Thema: 'Economie en Werk',
        "Thema's": 'Economie en Werk',
        'Verwant product': '',
        Labels:
          '4de maand, aanmoedegingspremie, aanmoediging, aanmoedigingspremie, aanmoedigingspremies, ap, tijdkrediet, vierde maand, vlaamse premie, awap',
        'Geldig van': 'ma, 08/03/2009 - 14:58',
        'Geldig tot': 'ma, 12/31/2035 - 01:00',
      },
      {
        PID: '227',
        Naam: 'Jaarlijkse verkeersbelasting voor personenwagens en aanverwante voertuigen',
        Titel:
          'Jaarlijkse verkeersbelasting voor personenwagens en aanverwante voertuigen',
        Inhoud:
          'De jaarlijkse verkeersbelasting is een gewestelijke belasting op motorvoertuigen die personen of goederen over de weg vervoeren. In Vlaanderen wordt de verkeersbelasting geend door de Vlaamse Belastingdienst.',
        Voorwaarden:
          "U betaalt een jaarlijkse verkeersbelasting vanaf de inschrijving van uw nieuw of tweedehandsvoertuig bij de Dienst Inschrijving Voertuigen (DIV). Tot de categorie personenwagens en aanverwante voertuigen behoren: personenauto's auto's voor dubbel gebruik (vervoer van personen en goederen) trage auto's voor dubbel gebruik minibussen ziekenwagens motorfietsen (ook driewielers en vierwielers) lichte vrachtauto's, een lijkwagen, tractor met een MTM tot en met 3500 kg aanhangwagens, boot- en kampeeraanhangwagens (caravan) van 750 kg tot 3500 kg kampeerauto's (mobilhomes) voertuigen met een transitplaat of tijdelijke nummerplaat.",
        Procedure:
          'Na de inschrijving van uw nieuw of tweedehandsvoertuig bij de Dienst Inschrijving Voertuigen (DIV), stelt de DIV de Vlaamse Belastingdienst op de hoogte van uw inschrijving. U ontvangt van de Vlaamse Belastingdienst automatisch jaarlijks een aanslagbiljet zolang uw voertuig blijft ingeschreven. U betaalt de verkeersbelasting vanaf de eerste dag van de maand van inschrijving . Als u meent dat uw verkeersbelasting niet correct is (bijv. de berekening), dan kunt u een bezwaar indien . Zodra u uw nummerplaat laat schrappen , moet u geen verkeersbelasting meer betalen. Op de website van de Vlaamse Belastingdienst kunt u zelf de status van uw dossier opvolgen via het digitaal loket .',
        'Wat meebrengen': '',
        Bedrag:
          'U kunt zelf berekenen hoeveel verkeersbelasting u zal moeten betalen via de online simulator of met de simulatie-app . De simulatie is louter indicatief en geeft niet het officiele bedrag. Het bedrag van de verkeersbelasting wordt: jaarlijks op 1 juli geendexeerd berekend op basis van de het vermogen (kW - kilowatt) van het voertuig, de euronorm en de CO2- uitstoot. Sinds 1 juli 2017 betalen de lichte vrachtwagens , lijkwagens, tractoren en trekkers met een MTM tot en met 3500 kg die geen leasing zijn, een groene jaarlijkse verkeersbelasting . De verkeersbelasting voor deze voertuigen kunt u momenteel nog niet online simuleren. Vermindering van de jaarlijkse verkeersbelasting Afhankelijk van het type voertuig of de activiteit van het voertuig is een vermindering van de jaarlijkse verkeersbelasting mogelijk. Sommige verminderingen krijgt u automatisch, andere moet u aanvragen . Soorten verminderingen: Terugbetaling gecombineerd vervoer Vermindering voor een autobus die deel uitmaakt van een wagenpark Forfaitaire vermindering voor LPG voertuigen (sinds aanslagjaar 2016) Vrijstelling van de jaarlijkse verkeersbelasting In bepaalde gevallen is een vrijstelling van de jaarlijkse verkeersbelasting mogelijk. Er bestaan verschillende soorten vrijstellingen : Vrijstelling occasioneel vervoer (rittenblad) Vrijstelling voor persoon met een handicap Vrijstelling voor bepaalde brandstoftypes sinds 01/07/2017 Vrijstelling voor bepaalde brandstoftypes (sinds aanslagjaar 2016)',
        Uitzonderingen:
          "Deze voertuigen zijn vrijgesteld van de jaarlijkse verkeersbelasting: voertuigen die uitsluitend worden gebruikt voor een openbare dienst (bijv. de Post, de brandweer, ziekenauto's, het leger, e) voertuigen die als persoonlijk vervoermiddel gebruikt door grootoorlogsinvaliden taxi's speedpedelecs, lichte vierwielers en motorfietsen met een cilinderinhoud < 251 cc die ingeschreven zijn bij de DIV landbouwvoertuigen als ze enkel gebruikt worden voor de landbouwarbeid",
        Regelgeving:
          'Op Vlaanderen.be vindt u meer informatie over de regelgeving voor de jaarlijkse verkeersbelasting.',
        'Websites / Publication URI':
          'Jaarlijkse verkeersbelasting (Vlaanderen.be) (https://www.vlaanderen.be/jaarlijkse-verkeersbelasting-vkb)',
        Documenten: '',
        'Bevoegde overheid': 'Vlaamse overheid',
        'Afleverende dienst': 'Vlaamse overheid',
        'Adres afleverende dienst':
          'Vlaamse Belastingdienst\nVaartstraat 16\n9300 Aalst\n',
        Type: 'Financiele verplichting',
        Doelgroep: 'Burger, Onderneming, Organisatie',
        'Geografische toepassingsgebied': 'Vlaamse Gewest',
        Thema: 'Mobiliteit en Openbare Werken',
        "Thema's": 'Mobiliteit en Openbare Werken',
        'Verwant product':
          'Vrijstelling van de belasting op inverkeerstelling en de verkeersbelasting (VKB) voor personen met een handicap en oorlogsinvaliden, Autokeuring',
        Labels:
          'geautomatiseerde, geautomatiseerde voertuigen, gv, lijkwagen, meer betalen, periode, groene verkeersbelasting, lichte, tractor, bestelwagen, bestelauto, autotax, autotaks, belasting, auto, autobelasting, speedpedelecs',
        'Geldig van': 'do, 08/19/2010 - 12:47',
        'Geldig tot': 'ma, 12/31/2035 - 01:00',
      },
      {
        PID: '531',
        Naam: 'Premie voor bestrijding van leegstand en verwaarlozing van bedrijfsruimten voor nieuwe eigenaars',
        Titel:
          'Premie voor bestrijding van leegstand en verwaarlozing van bedrijfsruimten voor nieuwe eigenaars',
        Inhoud:
          'Om leegstand en verwaarlozing van bedrijfsruimten, gelegen in het Vlaamse Gewest, tegen te gaan, kunt u een financiele tegemoetkoming krijgen voor het uitvoeren van saneringswerkzaamheden (sloop- en/of ontmantelingswerken). Het vastgoed moet wel opgenomen zijn in de Inventaris van leegstaande en/of verwaarloosde bedrijfsruimten.',
        Voorwaarden:
          "U kunt een premie krijgen zowel als natuurlijke persoon als als rechtspersoon (incl. vzw's) en als u aan volgende voorwaarden voldoet: Het onroerend goed moet 2 opeenvolgende jaren in de Inventaris zijn opgenomen. Als bewijs geldt het registratieattest. U mag ten hoogste 2 jaar de nieuwe eigenaar zijn van het onroerend goed op het moment van de premieaanvraag Het bedrag van de werkelijk gedragen saneringskosten moet minimum 24.750 euro zijn (excl. btw) De kadastrale oppervlakte moet ten minste 5 are zijn. Meer informatie over de voorwaarden kunt u nalezen op de website.",
        Procedure: '',
        'Wat meebrengen': '',
        Bedrag:
          'De financiele tegemoetkoming bedraagt: 60% van de kosten van de saneringswerken als de aanvrager aantoont dat het saneringsvoorstel en de te realiseren herbestemming substantieel bijdragen aan een of meer van volgende doelstellingen: de verhoging van het ruimtelijk rendement de ontharding en vergroening de transitie naar hernieuwbare energie en klimaatneutraliteit de versterking van de verweving van activiteiten, of van gedeeld of meervoudig ruimtegebruik 30% van de kosten van de saneringswerken in alle andere gevallen.',
        Uitzonderingen: '',
        Regelgeving: '',
        'Websites / Publication URI':
          'Premie leegstaande bedrijfsruimten (https://omgeving.vlaanderen.be/leegstaande-en-verwaarloosde-bedrijfsruimten)',
        Documenten: '',
        'Bevoegde overheid': 'Vlaamse overheid',
        'Afleverende dienst': 'Vlaamse overheid',
        'Adres afleverende dienst':
          'Departement Omgeving\nGraaf de Ferrarisgebouw\nKoning Albert II laan 20\n1000 Brussel\n',
        Type: 'Financieel voordeel',
        Doelgroep: 'Burger, Onderneming, Organisatie',
        'Geografische toepassingsgebied': 'Vlaamse Gewest',
        Thema: 'Economie en Werk',
        "Thema's": 'Economie en Werk',
        'Verwant product':
          'Heffing op de leegstand en verwaarlozing van bedrijfsgebouwen',
        Labels: 'bedrijfsgebouw, bedrijfsruimten, leegstand, subsidie',
        'Geldig van': 'wo, 01/18/2012 - 16:30',
        'Geldig tot': 'ma, 12/31/2035 - 01:00',
      },
      {
        PID: '2002',
        Naam: 'Subsidie verfraaing handelspanden',
        Titel: 'Subsidie verfraaing handelspanden',
        Inhoud:
          'De Stad Gent subsidieert renovaties aan handelspanden wanneer je werk maakt van een verzorgde gevel, toegankelijkheid, verbeteren van commerciele ruimte e Er wordt extra aandacht besteed aan werken die de toegankelijkheid voor personen met een fysieke beperking verbeteren en ook gezinsvriendelijke horeca wordt ondersteund. Verder worden verbeteringswerken aan de maak-/atelierruimtes verbonden aan een handelszaak gesubsidieerd.',
        Voorwaarden: '',
        Procedure: '',
        'Wat meebrengen': '',
        Bedrag: '',
        Uitzonderingen: '',
        Regelgeving: '',
        'Websites / Publication URI':
          'Subsidie verfraaing handelspanden (https://stad.gent/nl/ondernemen/ondersteuning-en-premies-voor-ondernemers/sectoroverschrijdend/subsidie-verfraaiing-handelspanden)',
        Documenten: '',
        'Bevoegde overheid': 'Lokale overheid',
        'Afleverende dienst': 'Lokale overheid',
        'Adres afleverende dienst': '',
        Type: 'Financieel voordeel',
        Doelgroep: 'Onderneming',
        'Geografische toepassingsgebied': 'Gemeente',
        Thema: 'Economie en Werk',
        "Thema's": 'Economie en Werk',
        'Verwant product': '',
        Labels: '',
        'Geldig van': 'vr, 10/08/2021 - 10:49',
        'Geldig tot': 'ma, 12/31/2035 - 01:00',
      },
      {
        PID: '2001',
        Naam: 'Starterscontract',
        Titel: 'Starterscontract',
        Inhoud:
          'Stad Gent kent een subsidie toe aan (her)startende ondernemers om hun slaagkansen te verhogen en de zelfstandige economische activiteit in de stad te verhogen. Onderteken een starterscontract en ontvang een subsidie van 5.000 euro voor investeringen, cursussen of professioneel advies.',
        Voorwaarden: '',
        Procedure: '',
        'Wat meebrengen': '',
        Bedrag: '',
        Uitzonderingen: '',
        Regelgeving: '',
        'Websites / Publication URI':
          'Starterscontract (https://stad.gent/nl/ondernemen/een-onderneming-starten-gent/starterscontract)',
        Documenten: '',
        'Bevoegde overheid': 'Lokale overheid',
        'Afleverende dienst': 'Lokale overheid',
        'Adres afleverende dienst': '',
        Type: 'Financieel voordeel',
        Doelgroep: 'Onderneming',
        'Geografische toepassingsgebied': 'Gemeente',
        Thema: 'Economie en Werk',
        "Thema's": 'Economie en Werk',
        'Verwant product': '',
        Labels: '',
        'Geldig van': 'do, 10/07/2021 - 10:11',
        'Geldig tot': 'ma, 12/31/2035 - 01:00',
      },
      {
        PID: '566',
        Naam: 'Belasting op de inverkeerstelling (BIV)',
        Titel: 'Belasting op de inverkeerstelling (BIV)',
        Inhoud:
          'De belasting op inverkeerstelling (BIV), ook soms inschrijvingstaks genoemd, is een eenmalige belasting die iedere eigenaar van een nieuw of tweedehands voertuig moet betalen vanaf de ingebruikname van het voertuig op de openbare weg in Belgie . In het Vlaamse gewest wordt de BIV geend door de Vlaamse Belastingdienst.',
        Voorwaarden:
          "De belasting op de inverkeerstelling (BIV) moet betaald worden voor personenauto's, minibussen en motorfietsen, boten en vliegtuigen , die ingeschreven zijn in Belgie.",
        Procedure:
          'Na de eerste inschrijving van uw voertuig bij de DIV (Dienst voor Inschrijvingen van Voertuigen) ontvangt u van de Vlaamse Belastingdienst automatisch een aanslagbiljet. Na ontvangst van het aanslagbiljet hebt u 2 maanden de tijd om de BIV te betalen.',
        'Wat meebrengen': '',
        Bedrag:
          'Voor de berekening van de BIV wordt er rekening gehouden met: De milieukenmerken van het voertuig waaronder CO2-uitstoot, uitstoot fijn stof, brandstoftype, euronorm en aanwezigheid roetfilter. De leeftijd van het voertuig volgens datum eerste inschrijving. U kunt zelf berekenen hoeveel BIV u moet betalen via de online simulator of met de simulatie-app . De simulatie is louter indicatief en geeft niet het officiele bedrag. Vrijstelling van de belasting op inverkeerstelling In bepaalde gevallen is een vrijstelling van de BIV mogelijk: Vrijstelling voor persoon met een handicap Vrijstelling voor de overdrach t tussen (ex-)echtgenoten of (ex-)wettelijk samenwonenden Vrijstelling van de belasting op inverkeerstelling en de verkeersbelasting wegens uitvoer van het voertuig Vrijstelling voor pure elektrische en pure waterstofvoertuigen Tijdelijke vrijstelling voor plug-in hybride voertuigen en CNG/LNG voertuigen Vrijstelling voor motorfietsen aangedreven op elektriciteit of waterstof. Deze vrijstelling geldt niet voor leasingbedrijven. Als u denkt in aanmerking te komen voor een vrijstelling, dan moet u dit aanvragen. Op de website van de Vlaamse Belastingdienst vindt u de formulieren om de vrijstelling aan te vragen of stop te zetten.',
        Uitzonderingen:
          'In de volgende gevallen is er geen BIV verschuldigd: Voor de herinschrijving van eenzelfde voertuig door dezelfde belastingplichtige (bijv. de firmanaam wijzigt maar het btw-nummer blijft hetzelfde of bij een wijziging van een nummerplaat omdat er meer dan twee adreswijzigingen op het inschrijvingsbewijs vermeld staan of bij een wijziging van een oude nummerplaat naar een Europese nummerplaat ). Voor de herinschrijving van eenzelfde voertuig op naam van de overlevende echtgenoot of wettelijk samenwonende partner als de titularis van het voertuig overleden is. Als het voertuig wordt heringeschreven op naam van een van de kinderen is er wel opnieuw BIV verschuldigd. Voor voertuigen met een handelaarsplaat (Z-plaat). Voor kampeerwagens (mobilhomes), lichte vrachtwagens en vrachtwagens met een MTT van meer dan 3,5 ton. Voor speedpedelecs en lichte vierwielers die ingeschreven zijn bij de DIV.',
        Regelgeving: '',
        'Websites / Publication URI':
          'Belasting op inverkeerstelling (https://belastingen.vlaanderen.be/belasting-op-inverkeerstelling)',
        Documenten: '',
        'Bevoegde overheid': 'Vlaamse overheid',
        'Afleverende dienst': 'Vlaamse overheid',
        'Adres afleverende dienst':
          'Vlaamse Belastingdienst\nVaartstraat 16\n9300 Aalst\n',
        Type: 'Financiele verplichting',
        Doelgroep: 'Burger, Onderneming, Organisatie',
        'Geografische toepassingsgebied': 'Vlaamse Gewest',
        Thema: 'Mobiliteit en Openbare Werken',
        "Thema's": 'Mobiliteit en Openbare Werken',
        'Verwant product': '',
        Labels:
          'biv, lichte vracht, overname overdracht, verkeersbelasting, scooter, cng, lng, uitvoer, fijnstof, inverkeersstelling, auto, autotaks, autotax, belasting, autobelasting, speed pedelecs, export, handelaarsplaat, inschrijvingstaks, boot',
        'Geldig van': 'do, 08/19/2010 - 12:40',
        'Geldig tot': 'ma, 12/31/2035 - 01:00',
      },
      {
        PID: '1436',
        Naam: 'Aanwervingsincentive voor langdurig werkzoekenden',
        Titel: 'Aanwervingsincentive voor langdurig werkzoekenden',
        Inhoud:
          'De aanwervingsincentive is een premie voor de werkgever die een langdurig werkzoekende in dienst neemt.',
        Voorwaarden:
          'De werknemer moet onder meer: op het ogenblik van indiensttreding minstens 2 jaar als niet-werkende werkzoekende ingeschreven zijn bij de VDAB. op het einde van het kwartaal van de indiensttreding 25 jaar of ouder en jonger dan 56 jaar zijn. Lees meer over de voorwaarden voor werkgever en werknemer .',
        Procedure:
          'De aanwervingsincentive kan alleen online aangevraagd worden. Dat moet binnen 3 maanden na indiensttreding gebeuren. Lees meer over de aanvraag van de aanwervingsincentive .',
        'Wat meebrengen': '',
        Bedrag:
          'De werkgever ontvangt de aanwervingsincentive in twee schijven : een eerste schijf van maximaal 1.250 euro als de werknemer drie maanden bij de onderneming werkt een tweede schijf van maximaal 3.000 euro als de werknemer een jaar bij de onderneming werkt. Lees meer over de uitbetaling van de aanwervingsincentive.',
        Uitzonderingen: '',
        Regelgeving: '',
        'Websites / Publication URI': '',
        Documenten: '',
        'Bevoegde overheid': 'Vlaamse overheid',
        'Afleverende dienst': 'Vlaamse overheid',
        'Adres afleverende dienst':
          'Aanwervingsincentive langdurig werkzoekenden\nEllipsgebouw\nKoning Albert II laan 35\n1030 Schaarbeek\n',
        Type: 'Financieel voordeel',
        Doelgroep: 'Onderneming',
        'Geografische toepassingsgebied': 'Vlaamse Gewest',
        Thema: 'Economie en Werk',
        "Thema's": 'Economie en Werk',
        'Verwant product':
          'Doelgroepvermindering laaggeschoolde jongeren, Vlaamse doelgroepvermindering voor oudere werknemers',
        Labels:
          'landurig werklozen, langdurig, activa, activaplan, aanwervingspremie, awi, premie aanwerving, incentive, insentive, aanwervingsstimulans, wervingspremie, wervingsincentive, aanwerving',
        'Geldig van': 'di, 01/24/2017 - 17:33',
        'Geldig tot': 'ma, 12/31/2035 - 01:00',
      },
      {
        PID: '334',
        Naam: 'Praktijkgerichte ondernemerschapstrajecten (Syntra)',
        Titel: 'Praktijkgerichte ondernemerschapstrajecten (Syntra)',
        Inhoud:
          'Ondernemende mensen ((pre)starters, gevestigde ondernemers en hun medewerkers) kunnen hun kennis en hun competenties aanscherpen met het arbeidsmarktgerichte en innovatieve opleidingsaanbod van het SYNTRA-netwerk.',
        Voorwaarden:
          'Er zijn meer dan 500 ondernemerschapstrajecten, onderverdeeld in 28 sectoren, zowel in dag- als in avondformule. De praktijkgerichte aanpak staat ervoor garant dat u de kennis die u in een opleiding opdoet, ook meteen professioneel kunt toepassen. Het opleidingsaanbod is er voor bestaande en toekomstige ondernemers (die niet meer leerplichtig zijn). Het aanbod geldt ook voor inwoners van het Brusselse Hoofdstedelijke Gewest die het Nederlands machtig zijn.',
        Procedure:
          'Het SYNTRA-netwerk bestaat uit 5 opleidingscentra, met meer dan 20 SYNTRA-campussen, verspreid over heel Vlaanderen. Het aanbod aan opleidingen vindt u op de website van elk opleidingscentrum. U vindt alle details over elke opleiding online en u kunt zich ook online inschrijven.',
        'Wat meebrengen': '',
        Bedrag:
          'Voor de meeste opleidingen kunt u, als u aan de voorwaarden voldoet, gebruikmaken van opleidingscheques (als werknemer) of de kmo-portefeuille (als zelfstandige).',
        Uitzonderingen: '',
        Regelgeving: '',
        'Websites / Publication URI':
          'Praktijkgerichte ondernemingsopleiding (http://www.syntra.be)',
        Documenten: '',
        'Bevoegde overheid': 'Vlaamse overheid',
        'Afleverende dienst': 'Vlaamse overheid',
        'Adres afleverende dienst':
          'Agentschap Innoveren en Ondernemen\nEllipsgebouw\nKoning Albert II laan 35\n1030 Schaarbeek\n',
        Type: 'Advies en begeleiding',
        Doelgroep: 'Burger, Onderneming, Organisatie',
        'Geografische toepassingsgebied':
          'Brusselse Hoofdstedelijke Gewest, Vlaamse Gewest',
        Thema: 'Economie en Werk',
        "Thema's": 'Economie en Werk',
        'Verwant product':
          "Subsidie voor opleiding en advies voor kmo's en zelfstandigen (kmo-portefeuille)",
        Labels:
          'attest kennis bedrijfsbeheer, bedrijfsbeheer, beroepsopleiding, ondernemersvorming, syntra, extra opleiding, opleiding, werknemer, zelfstandige',
        'Geldig van': 'ma, 08/17/2009 - 09:42',
        'Geldig tot': 'ma, 12/31/2035 - 01:00',
      },
      {
        PID: '1728',
        Naam: 'Limosa-aangifte',
        Titel: 'Limosa-aangifte',
        Inhoud:
          'Bent u een werkgever en geeft u een werknemer een opdracht in Belgie? Bent u zelfstandige en komt u voor een opdracht naar Belgie? In beide gevallen moet u dat melden door de zogenaamde Limosa in te vullen. De Limosa-aangifte bevat een hoop informatie over de werknemer en de werkgever (arbeidsplaats, duur van de detachering, werkroosters, enz.). Na aangifte wordt meteen een ontvangstbewijs Limosa-1 afgeleverd. Iedereen die niet onderworpen is aan de Belgische sociale zekerheid en die tijdelijk en/of deeltijds in Belgie komt werken, moet een meldingsbewijs Limosa-1 kunnen voorleggen aan zijn Belgische klant of opdrachtgever. Dat moet gebeuren voordat het werk begint.',
        Voorwaarden:
          'Voor wie? Limosa is bestemd voor werknemers die tijdelijk of deeltijds in Belgie komen werken. Het gaat met andere woorden om: werknemers die gewoonlijk in een ander land dan Belgie werken die in een ander land dan Belgie zijn aangeworven. zelfstandigen die tijdelijk een zelfstandige activiteit in Belgie komen uitoefenen, maar er niet permanent verblijven. Er bestaan verschillende vrijstellingen op deze algemene verplichting. Die hangen af van de redenen van de komst naar Belgie en de duur van het verblijf.',
        Procedure:
          'U moet het meldingsbewijs Limosa-1 kunnen voorleggen veer het begin van het werk in Belgie . Als de opdracht langer duurt dan oorspronkelijk was aangegeven, moet u een nieuwe aangifte indienen. Een Limosa-aangifte invoeren, verlengen of annuleren doet u online. Voordat u toegang krijgt tot de beveiligde onlinedienst Limosa, maakt u een gebruikersaccount aan. Daarna dient u voor elke opdracht een Limosa-aangifte in. U hebt daarvoor bepaalde gegevens nodig .',
        'Wat meebrengen': '',
        Bedrag: '',
        Uitzonderingen: '',
        Regelgeving: '',
        'Websites / Publication URI':
          'Limosa-aangifte (https://www.international.socialsecurity.be/working_in_belgium/nl/limosa.html)',
        Documenten: '',
        'Bevoegde overheid': 'Federale overheid',
        'Afleverende dienst': 'Federale overheid',
        'Adres afleverende dienst':
          'Contactcenter Sociale Zekerheid voor Ondernemers\nAdministratief Centrum Kruidtuin, Finance Tower\nKruidtuinlaan 50 bus 100\n1000 Brussel',
        Type: 'Bewijs',
        Doelgroep: 'Onderneming',
        'Geografische toepassingsgebied': 'Federaal',
        Thema: 'Economie en Werk',
        "Thema's": 'Economie en Werk',
        'Verwant product': 'Erkenning als uitzendbureau',
        Labels:
          'meldingsbewijs, sociale documenten, meldingsplicht, detachering, valse detachering, gedetacheerd',
        'Geldig van': 'di, 11/28/2017 - 20:03',
        'Geldig tot': 'ma, 12/31/2035 - 01:00',
      },
      {
        PID: '739',
        Naam: 'Hygieneattest',
        Titel: 'Hygieneattest',
        Inhoud:
          'Het hygieneattest bevestigt dat uw zaak voldoet aan de hygienische eisen. U vraagt het attest aan: bij de opening van een nieuwe zaak: in een nieuwbouw als er een bestemmingswijziging van het onroerend goed plaatsvindt als de aard van de handelsactiviteit wijzigt als er in een bestaande horecazaak een verbouwing met bouwtoelating gebeurt, voor dat gedeelte waarop de bouwtoelating betrekking heeft. bij heropening van een zaak: als de zaak langer dan 1 jaar gesloten was als de bestemming is gewijzigd als er (ook binnen) veranderingswerken werden uitgevoerd. Zolang u geen nieuwe aangifte voor de openingsbelasting nodig hebt, blijft het hygieneattest geldig.',
        Voorwaarden: '',
        Procedure:
          'U vraagt het attest minimaal 15 dagen voor de opening van uw horecazaak aan in de gemeente waar uw zaak ligt.',
        'Wat meebrengen': '',
        Bedrag: '',
        Uitzonderingen: '',
        Regelgeving: '',
        'Websites / Publication URI': '',
        Documenten: '',
        'Bevoegde overheid': 'Federale overheid',
        'Afleverende dienst': 'Lokale overheid',
        'Adres afleverende dienst': '',
        Type: 'Bewijs',
        Doelgroep: 'Burger, Onderneming, Organisatie',
        'Geografische toepassingsgebied': 'Federaal',
        Thema: 'Economie en Werk',
        "Thema's": 'Economie en Werk',
        'Verwant product':
          'Vergunning voor het verstrekken van gegiste en/of sterke dranken, Moraliteitsattest',
        Labels: 'horeca, hygiene',
        'Geldig van': 'di, 05/21/2013 - 15:38',
        'Geldig tot': 'ma, 12/31/2035 - 01:00',
      },
      {
        PID: '1486',
        Naam: 'Transitiepremie voor startende ondernemers',
        Titel: 'Transitiepremie voor startende ondernemers',
        Inhoud:
          'Bent u een niet-werkende werkzoekende en wilt u een eigen zaak oprichten? Onder bepaalde voorwaarden kunt u twee jaar lang een premie krijgen terwijl u uw zaak opstart.',
        Voorwaarden:
          'Om in aanmerking te komen voor de transitiepremie, moet u voldoen aan de onderstaande voorwaarden. U bent zelfstandige zijn in hoofdberoep. U bent bij VDAB ingeschreven als niet-werkende werkzoekende. U bent uitkeringsgerechtigd volledig werkloos. U hebt met succes een prestarterstraject afgerond voordat u start als zelfstandige in hoofdberoep. .Uw zaak ligt in het Vlaams Gewest. U werkt niet voor uw laatste werkgever. Lees meer over de voorwaarden voor de transitiepremie .',
        Procedure:
          'U vraag de transitiepremie online aan. Doe dat ten laatste 3 maanden nadat u gestart bent als zelfstandige in hoofdberoep. Anders komt u niet meer in aanmerking voor de premie. Vraag de transitiepremie aan .',
        'Wat meebrengen': '',
        Bedrag:
          'De transitiepremie is een maandelijkse bruto premie die u maximaal 2 jaar lang kunt krijgen. Het eerste kwartaal ontvangt u iets meer dan 500 euro per maand. Dat bedrag daalt elk kwartaal tot ruim 300 euro per maand in het laatste kwartaal. Bekijk de evolutie van de kwartaalbedragen .',
        Uitzonderingen: '',
        Regelgeving: '',
        'Websites / Publication URI': '',
        Documenten: '',
        'Bevoegde overheid': 'Vlaamse overheid',
        'Afleverende dienst': 'Vlaamse overheid',
        'Adres afleverende dienst':
          'Transitiepremie\nEllipsgebouw\nKoning Albert II laan 35\n1030 Schaarbeek\n',
        Type: 'Financieel voordeel',
        Doelgroep: 'Burger, Onderneming',
        'Geografische toepassingsgebied': 'Vlaamse Gewest',
        Thema: 'Economie en Werk',
        "Thema's": 'Economie en Werk',
        'Verwant product': '',
        Labels:
          '55, 55plus, 55plusser, 55-plusser, werkhervatting, werkhervattingstoeslag, werkhervattingspremie, acco-werkhervattingstoeslag, werkhervattingsbonus, werkhervattingsgeld, premie 50+, premie 55, oudere werklozen, starters, premie starters, starter, startpremie, starterspremie, premie starten, beginnen als zelfstandige, 45, 45+, 45-plussers, werkloosheid',
        'Geldig van': 'ma, 03/05/2018 - 12:47',
        'Geldig tot': 'ma, 12/31/2035 - 01:00',
      },
      {
        PID: '961',
        Naam: 'Beroepskaart voor vreemdelingen',
        Titel: 'Beroepskaart voor vreemdelingen',
        Inhoud:
          'Als u zich als buitenlandse onderdaan in Belgie als zelfstandige wilt vestigen, dan moet u een beroepskaart hebben. De beroepskaart geeft u de toestemming een zelfstandige activiteit uit te oefenen. Een aantal categorieen van buitenlanders is vrijgesteld van beroepskaart. De beroepskaart volstaat op zich niet om u als zelfstandige te vestigen. In bepaalde gevallen zal ook bepaalde kennis worden geeist. Het ondernemingsloket helpt zelfstandigen in spe bij die stappen.',
        Voorwaarden:
          'De beroepskaart is noodzakelijk voor iedereen die een zelfstandige activiteit wil aanvatten en die: niet de Belgische nationaliteit heeft niet de nationaliteit van een van de lidstaten van de EER heeft (de EU-landen plus IJsland, Noorwegen en Liechtenstein) niet de Zwitserse nationaliteit heeft om andere redenen geen vrijstelling heeft voor deze formaliteit.',
        Procedure:
          "Als u als buitenlandse zelfstandige een beroepskaart wilt verkrijgen, wijzigen, hernieuwen of vervangen, dan dient u een aanvraag in bij: de Belgische diplomatieke of consulaire post in het land van verblijf, als u in het buitenland verblijft een erkend ondernemingsloket naar keuze als u over een geldig verblijf in Belgie beschikt. Als geldig verblijf worden aanvaard: een 'attest van immatriculatie model A' een 'bewijs van inschrijving in het vreemdelingenregister' (= elektronische verblijfskaart type A). Als u om veiligheidsredenen de aanvraag niet in het land van verblijf kunt indienen, kunt u de aanvraag indienen bij een Belgische diplomatieke of consulaire post in een ander land bij een ondernemingsloket. Die laatste mogelijkheid vereist het voorafgaandelijke akkoord van de bevoegde regiominister en van de minister van Binnenlandse Zaken. Zij moet aangevraagd worden bij de bevoegde minister en gemotiveerd en vergezeld zijn van elk bewijsstuk dat de situatie bevestigt.",
        'Wat meebrengen': '',
        Bedrag: '',
        Uitzonderingen: '',
        Regelgeving: '',
        'Websites / Publication URI': '',
        Documenten: '',
        'Bevoegde overheid': 'Vlaamse overheid',
        'Afleverende dienst': 'Vlaamse overheid',
        'Adres afleverende dienst':
          'Team Beroepskaarten\nEllipsgebouw\nKoning Albert II laan 35\n1030 Schaarbeek\n',
        Type: 'Toelating',
        Doelgroep: 'Burger, Onderneming',
        'Geografische toepassingsgebied': 'Vlaamse Gewest',
        Thema: 'Economie en Werk',
        "Thema's": 'Economie en Werk',
        'Verwant product': '',
        Labels:
          'allochtoon, arbeidsmigrant, beginnen als zelfstandige, buitenlander, economische migratie, nachtwinkel, nightshop, vestigingsvoorwaarden, vreemde, vreemdeling, werken als buitenlander, werken als vreemdeling',
        'Geldig van': 'ma, 06/23/2014 - 22:17',
        'Geldig tot': 'ma, 12/31/2035 - 01:00',
      },
      {
        PID: '1834',
        Naam: 'Europese blauwe kaart voor hoogopgeleide vreemdelingen',
        Titel: 'Europese blauwe kaart voor hoogopgeleide vreemdelingen',
        Inhoud:
          'Hoogopgeleide buitenlanders kunnen onder bepaalde voorwaarden gedurende meer dan 90 dagen in Vlaanderen wonen en werken. In dat geval kan hun toekomstige werkgever een Europese blauwe kaart voor hen aanvragen.',
        Voorwaarden:
          'Met een Europese blauwe kaart kan een werknemer die niet de nationaliteit van een lidstaat van de EER of Zwitserland heeft, meer dan 90 dagen in Belgie werken en verblijven. De regelgeving is de omzetting van de Europese Richtlijn (van 2009/50 van 25 mei 2009) voor de voorwaarden voor toegang en verblijf van onderdanen van derde landen met het oog op een hooggekwalificeerde baan.',
        Procedure:
          'De toekomstige werkgever vraagt de Europese blauwe kaart aan.',
        'Wat meebrengen': '',
        Bedrag: '',
        Uitzonderingen: '',
        Regelgeving: '',
        'Websites / Publication URI': '',
        Documenten: '',
        'Bevoegde overheid': 'Vlaamse overheid',
        'Afleverende dienst': 'Vlaamse overheid',
        'Adres afleverende dienst':
          'Team Arbeidskaarten Antwerpen\nAnna Bijnsgebouw\nLange Kievitstraat 111\n2018 Antwerpen\n, Team arbeidskaarten Brussel\nEllipsgebouw\nKoning Albert II laan 35\n1030 Schaarbeek\n, Team Arbeidskaarten Gent\nVirginie Lovelinggebouw\nKoningin Maria Hendrikaplein 70\n9000 Gent\n, Team Arbeidskaarten Leuven\nDirk Boutsgebouw\nDiestsepoort 6\n3000 Leuven',
        Type: 'Toelating',
        Doelgroep: 'Burger, Onderneming',
        'Geografische toepassingsgebied':
          'Brusselse Hoofdstedelijke Gewest, Vlaamse Gewest',
        Thema: 'Economie en Werk',
        "Thema's": 'Economie en Werk',
        'Verwant product': '',
        Labels: 'EBK, derdelander, derdelanders, h kaart, h-kaart',
        'Geldig van': 'vr, 10/10/2014 - 17:17',
        'Geldig tot': 'ma, 12/31/2035 - 01:00',
      },
      {
        PID: '1976',
        Naam: 'Toelating tot arbeid voor buitenlandse werknemers',
        Titel: 'Toelating tot arbeid voor buitenlandse werknemers',
        Inhoud:
          'Als u als werkgever een buitenlandse werknemer in loondienst wilt aanwerven, moet u daar vooraf een toelating tot arbeid voor aanvragen.',
        Voorwaarden:
          'Het soort werk dat de buitenlander zal verrichten, bepaalt of hij zal worden toegelaten tot de arbeidsmarkt. Een toelating tot arbeid kan alleen worden toegekend als het werk van de buitenlander tot een welbepaalde categorie behoort. Voor elke categorie gelden aparte voorwaarden en procedures. Door enkele vragen te beantwoorden , kunt u nagaan via welke categorie van werknemer u mogelijk in aanmerking komt voor een toelating tot arbeid. Voor bepaalde categorieen van buitenlanders is er geen toelating tot arbeid vereist , bijvoorbeeld als het gaat om onderdanen van een EU-lidstaat of van IJsland, Noorwegen, Liechtenstein of Zwitserland. Zij mogen om het even welke job uitoefenen in Vlaanderen, bij om het even welke werkgever.',
        Procedure:
          'Afhankelijk van de periode die de buitenlandse werknemer in Vlaanderen za werken, vraagt u de toelating tot arbeid aan per e-mail of via het uniek loket .',
        'Wat meebrengen': '',
        Bedrag: '',
        Uitzonderingen: '',
        Regelgeving: '',
        'Websites / Publication URI': '',
        Documenten: '',
        'Bevoegde overheid': 'Vlaamse overheid',
        'Afleverende dienst': 'Vlaamse overheid',
        'Adres afleverende dienst': '',
        Type: 'Toelating',
        Doelgroep: 'Onderneming',
        'Geografische toepassingsgebied': 'Vlaamse Gewest',
        Thema: 'Economie en Werk',
        "Thema's": 'Economie en Werk',
        'Verwant product': '',
        Labels: '',
        'Geldig van': 'do, 06/03/2021 - 14:59',
        'Geldig tot': 'ma, 12/31/2035 - 01:00',
      },
      {
        PID: '1671',
        Naam: 'Springplank naar zelfstandige',
        Titel: 'Springplank naar zelfstandige',
        Inhoud:
          "Ontvangt u een werkloosheids- of inschakelingsuitkering en wilt u een eigen zaak oprichten? Met de maatregel 'Springplank naar zelfstandige' kunt u 12 maanden lang als zelfstandige in bijberoep werken zonder dat u uw uitkering verliest. Met de maatregel wil de overheid ondernemers in spe stimuleren om de sprong naar het ondernemerschap te wagen.",
        Voorwaarden:
          "Wie? U komt in aanmerking voor de maatregel 'Springplank naar zelfstandige' als u aan deze vijf voorwaarden voldoet. U ontvangt een een werkloosheids- of inschakelingsuitkering. U komt niet in aanmerking als u in uw beroepsinschakelingstijd zit. U doet aangifte bij de RVA van uw zelfstandige nevenactiviteit veer het begin van die activiteit (of, als u nog geen werkloosheids- of inschakelingsuitkering ontvangt, op het moment dat u uw uitkering aanvraagt). U bent niet opzettelijk werkloos geworden om deze premie te kunnen krijgen. U hebt uw nevenactiviteit niet als zelfstandig hoofdberoep uitgeoefend in de afgelopen zes jaar. U werft geen personeel aan voor uw zelfstandige nevenactiviteit. Welke zelfstandige activiteit? Het mag geen artistieke activiteit zijn. Het moet een nevenactiviteit zijn. Dat betekent dat het aantal uur dat u eraan besteedt en de grootte van uw inkomsten beperkt moeten zijn. De RVA oordeelt of dat het geval is of niet. U mag de activiteit zowel overdag als 's avonds uitoefenen. Plichten Als u een beroep doet op de maatregel 'Springplank naar zelfstandige', moet u: ingeschreven zijn als werkzoekende bij de VDAB. beschikbaar zijn voor de arbeidsmarkt. Dat wil zeggen dat u onmiddellijk moet kunnen ingaan op een passende vacature, begeleiding of opleiding die uw VDAB-bemiddelaar u aanbiedt, en dat u uw afspraken met uw VDAB-bemiddelaar moet nakomen. in Belgie verblijft.",
        Procedure:
          'U vult de RVA-formulieren C1 en C1C in en bezorgt ze aan uw uitbetalingsinstelling.',
        'Wat meebrengen': '',
        Bedrag: '',
        Uitzonderingen: '',
        Regelgeving: '',
        'Websites / Publication URI':
          'Springplank naar zelfstandige (op RVA.be) (http://www.rva.be/nl/documentatie/infoblad/t158)',
        Documenten: '',
        'Bevoegde overheid': 'Federale overheid',
        'Afleverende dienst': 'Federale overheid',
        'Adres afleverende dienst':
          'Rijksdienst voor Arbeidsvoorziening\nKeizerslaan 7\n1000 Brussel\n',
        Type: 'Financieel voordeel',
        Doelgroep: 'Burger, Onderneming',
        'Geografische toepassingsgebied': 'Federaal',
        Thema: 'Economie en Werk',
        "Thema's": 'Economie en Werk',
        'Verwant product':
          'Werkloosheidsuitkering, Inschakelingsuitkering voor werkzoekende schoolverlaters',
        Labels: '',
        'Geldig van': 'ma, 03/19/2018 - 20:07',
        'Geldig tot': 'ma, 12/31/2035 - 01:00',
      },
      {
        PID: '1369',
        Naam: 'Innovatiepremie voor creatieve werknemers',
        Titel: 'Innovatiepremie voor creatieve werknemers',
        Inhoud:
          'Met de innovatiepremie kan een werkgever een financiele vergoeding geven aan een werknemer die binnen het bedrijf een vernieuwend idee heeft aangebracht. Die vergoeding is, als aan de voorwaarden wordt voldaan, vrijgesteld van socialezekerheidsbijdragen en wordt niet belast. De maatregel is verlengd tot eind 2020.',
        Voorwaarden: '',
        Procedure: '',
        'Wat meebrengen': '',
        Bedrag: '',
        Uitzonderingen: '',
        Regelgeving: '',
        'Websites / Publication URI':
          'Innovatiepremie  (http://economie.fgov.be/nl/themas/ondernemingen/een-onderneming-beheren-en/ondersteuning-en-premies/innovatiepremie)',
        Documenten: '',
        'Bevoegde overheid': 'Federale overheid',
        'Afleverende dienst': 'Federale overheid',
        'Adres afleverende dienst': '',
        Type: 'Financieel voordeel',
        Doelgroep: 'Burger, Onderneming',
        'Geografische toepassingsgebied': 'Federaal',
        Thema: 'Economie en Werk',
        "Thema's": 'Economie en Werk',
        'Verwant product': '',
        Labels:
          'belastingvrije bonus, beloning, creatieve, innovatie, innovatieve werknemer, procesinnovatie, productinnovatie, undefined',
        'Geldig van': 'di, 08/18/2015 - 18:24',
        'Geldig tot': 'ma, 12/31/2035 - 01:00',
      },
      {
        PID: '1664',
        Naam: 'Geregistreerde-kassasysteem in de horeca',
        Titel: 'Geregistreerde-kassasysteem in de horeca',
        Inhoud:
          "Om btw-fraude tegen te gaan, moeten bepaalde horecazaken met een 'witte' kassa werken. Het geregistreerde-kassasysteem (GKS) houdt alle bewerkingen bij die in de kassa worden ingevoerd.",
        Voorwaarden:
          'De verplichting om met een geregistreerde kassa te werken, geldt voor elke exploitant van een inrichting waar maaltijden worden verbruikt en elke traiteur die regelmatig cateringdiensten verricht. Een bijkomende voorwaarde is dat de jaaromzet voor die restaurant- en cateringdiensten, exclusief btw, hoger is dan 25.000 euro . Als u in dat geval verkeert, moet u dus een btw-kasticket uitreiken via een geregistreerde-kassasysteem (GKS). Lager dan 25.000 euro Is uw omzet lager dan 25.000 euro per kalenderjaar? Dan hoeft u geen GKS te gebruiken. U moet wel een btw-ontvangstbewijs uitreiken voor alle verbruikte maaltijden en bijhorende dranken. Om te bepalen of u boven of onder de grens van 25.000 euro zit, baseert u zich op uw omzetgegevens van het vorige kalenderjaar of, als het om een nieuwe zaak gaat, op de omzetprognose in uw businessplan.',
        Procedure: 'Lees meer over het geregistreerde-kassasysteem .',
        'Wat meebrengen': '',
        Bedrag: '',
        Uitzonderingen: '',
        Regelgeving: '',
        'Websites / Publication URI':
          'Geregistreerde-kassasysteem voor de horeca (https://www.geregistreerdkassasysteem.be)',
        Documenten: '',
        'Bevoegde overheid': 'Federale overheid',
        'Afleverende dienst': 'Federale overheid',
        'Adres afleverende dienst':
          'Federale Overheidsdienst Financien\nNorth Galaxy\nKoning Albert II laan 33\n1030 Schaarbeek\n',
        Type: 'Voorwerp',
        Doelgroep: 'Onderneming',
        'Geografische toepassingsgebied': 'Federaal',
        Thema: 'Economie en Werk',
        "Thema's": 'Economie en Werk',
        'Verwant product': '',
        Labels:
          '10 procent, 10-procent, black box, blackbox, smartcard, tienprocentregel, witte kassa, zwarte kas, zwarte kassa, zwarte omzet, snacks, witte kas, horecazaak',
        'Geldig van': 'vr, 11/29/2013 - 15:12',
        'Geldig tot': 'ma, 12/31/2035 - 01:00',
      },
      {
        PID: '751',
        Naam: 'Omgevingsvergunning voor kleinhandelsactiviteiten',
        Titel: 'Omgevingsvergunning voor kleinhandelsactiviteiten',
        Inhoud:
          'Wilt u een permanente handelszaak openen van meer dan 400me netto handelsoppervlakte in een bestaand gebouw, of voorziet u handelsactiviteiten voor in totaal meer dan 400me netto handelsoppervlakte in uw bouwproject, dan hebt u daarvoor een omgevingsvergunning voor kleinhandelsactiviteiten nodig.',
        Voorwaarden: '',
        Procedure:
          'U vraagt de vergunning aan bij de gemeente van de plaats van vestiging. Het college van burgemeester en schepenen reikt de machtiging uit. Als de machtiging deel uitmaakt van een omgevingsproject (stedenbouwkundige handelingen of exploitatie van ingedeelde inrichtingen of activiteiten), moet de aanvraag online gebeuren via het Omgevingsloket .',
        'Wat meebrengen': '',
        Bedrag: '',
        Uitzonderingen: '',
        Regelgeving:
          'Decreet van 15 juli 2016 betreffende het integraal handelsvestigingsbeleid',
        'Websites / Publication URI':
          'Omgevingsvergunning voor kleinhandelsactiviteiten (https://www.vlaio.be/nl/begeleiding-advies/vergunningen-getuigschriften/sector-overschrijdende-vergunningen-0)',
        Documenten: '',
        'Bevoegde overheid': 'Vlaamse overheid',
        'Afleverende dienst': 'Lokale overheid',
        'Adres afleverende dienst':
          'Team Ruimtelijke Economie\nEllipsgebouw\nKoning Albert II laan 35\n1030 Schaarbeek\n',
        Type: 'Toelating',
        Doelgroep: 'Onderneming',
        'Geografische toepassingsgebied': 'Vlaamse Gewest',
        Thema: 'Economie en Werk',
        "Thema's": 'Economie en Werk',
        'Verwant product': '',
        Labels:
          '1000 me, 400 me, NSECD, Nationaal Sociaal-Economisch Comite voor de Distributie, handelsvestiging, ikea, ikea-wet, sociaal-economische toelating, sociaal-economische vergunning, sociaaleconomische machtiging, sociaaleconomische toelating, sociaaleconomische vergunning, socio-economische machtiging, socio-economische toelating, socio-economische vergunning, toegang, toegang beroep, toegang tot het beroep, kleinhandelsvergunning, kleinhandelszaak',
        'Geldig van': 'di, 01/20/2015 - 16:32',
        'Geldig tot': 'ma, 12/31/2035 - 01:00',
      },
      {
        PID: '964',
        Naam: 'Startlening',
        Titel: 'Startlening',
        Inhoud:
          'Bent u werkloos en hebt u plannen voor een eigen zaak? Dan kunt u bij de opstart van uw zaak een beroep doen op de Startlening van PMV/z (het vroegere Participatiefonds-Vlaanderen). Met die Startlening+ kunt u tegen een voordelig tarief tot 100.000 euro lenen. Het gaat om een achtergestelde lening: dat betekent dat u bij geldproblemen PMV/z maar als laatste schuldeiser hoeft te vergoeden. Dat geeft andere schuldeisers (bijvoorbeeld banken) meer zekerheid.',
        Voorwaarden:
          "Corona In het kader van de coronacrisis verleent PMV/z een betalingsuitstel aan alle klanten die een Startlening, Cofinanciering of Cofinanciering+ hebben gekregen. Voorwaarden De Startlening is bestemd voor alle starters , ook voor werkzoekenden die een eigen zaak beginnen. Dat houdt in dat u nog nooit of niet langer dan 4 jaar zelfstandige in hoofdberoep bent geweest. Als het om een vennootschap gaat, wordt gekeken naar de voorgeschiedenis van de vennoten. Ook studenten-ondernemers kunnen een Startlening krijgen. U woont in het Vlaamse Gewest of uw maatschappelijke zetel is er gevestigd, en u kunt u investeren in een project op Belgisch grondgebied. Ligt uw woonplaats of uw maatschappelijke zetel niet in het Vlaamse Gewest, maar investeert u in het Vlaamse Gewest, dan komt u ook in aanmerking. U beantwoordt aan de Europese kmo-definitie . Vzw's kunnen in aanmerking komen als ze minstens de helft van hun inkomsten uit normale economische activiteiten halen. Bij de start van een eigen zaak mag u de lening gebruiken voor materiele investeringen, zoals bureaumateriaal, computers, machines e voor immateriele of financiele investeringen, zoals de overname van een bestaande handelszaak. De duur van de lening is minimaal 3 jaar (5 jaar als u werkzoekende bent) en maximaal tien jaar. Als u als werkzoekende de Startlening aangaat, hoeft u geen waarborgen te geven kan een schuld tot zelfs 40.000 euro u worden kwijtgescholden als u binnen drie maanden na de stopzetting van uw zaak kunt aantonen dat uw zaak onleefbaar was behoudt u uw recht op werkloosheidsuitkering als u, om welke reden ook, uw zaak binnen 15 jaar na aanvang stopzet. U kunt de Startlening cumuleren met een Kmo-cofinanciering van PMV/z, maar het bedrag van alle leningen samen mag niet hoger liggen dan 350.000 euro. Als u de Kmo-cofinanciering op naam van een vennootschap vraagt, moet u de tegenwaarde van de Startlening+ en de eigen inbreng onder de vorm van volstort kapitaal inbrengen in de vennootschap.",
        Procedure:
          'Voor aanvragen en begeleiding bij de indiening van de Startlening kunt u zich wenden tot de aanbrengers of kredietinstellingen waarmee PMV/z samenwerkt. Op de website van PMV/Z vindt u een lijst per provincie . Rechtstreeks indienen bij PMV/z is ook mogelijk.',
        'Wat meebrengen': '',
        Bedrag:
          'Het maximumbedrag van de lening is gelijk aan het kleinste van volgende bedragen: vier keer de eigen inbreng: dat bedrag mag ook gedeeltelijk of volledig geleend worden. 100.000 euro. In principe is er geen minimumbedrag, maar PMV/z gaat ervan uit dat aanvragen van minder dan 5.000 euro beter op een andere manier gefinancierd kunnen worden. U betaalt de Startlening maandelijks terug met constante aflossingen. De intrestvoet is vast en bedraagt nu 3 procent per jaar.',
        Uitzonderingen: '',
        Regelgeving: '',
        'Websites / Publication URI':
          'Startlening (http://www.pmvz.eu/startlening)',
        Documenten: '',
        'Bevoegde overheid': 'Vlaamse overheid',
        'Afleverende dienst': 'Vlaamse overheid',
        'Adres afleverende dienst':
          'Agentschap Innoveren en Ondernemen\nEllipsgebouw\nKoning Albert II laan 35\n1030 Schaarbeek\n, PMV/z-Leningen\nOude Graanmarkt 63\n1000 Brussel',
        Type: 'Financieel voordeel',
        Doelgroep: 'Burger, Onderneming',
        'Geografische toepassingsgebied': 'Vlaamse Gewest',
        Thema: 'Economie en Werk',
        "Thema's": 'Economie en Werk',
        'Verwant product': 'Ondersteuning voor huisartsen',
        Labels:
          'jonge zelfstandigen, plan jonge zelfstandigen, starters, startkapitaal, starterslening',
        'Geldig van': 'do, 11/14/2013 - 11:18',
        'Geldig tot': 'ma, 12/31/2035 - 01:00',
      },
      {
        PID: '1849',
        Naam: 'Toelage handelaarsvereniging',
        Titel: 'Toelage handelaarsvereniging',
        Inhoud:
          'Handelaars in een stad of gemeente kunnen zich verenigen in een handelaarsvereniging. Een handelaarsvereniging kan onder bepaalde voorwaarden in aanmerking komen voor een of meerdere toelagen van de stad of de gemeente.',
        Voorwaarden: '',
        Procedure:
          'Of en hoe u een beroep kunt doen op lokale maatregelen kunt u nagaan bij uw stad of gemeente.',
        'Wat meebrengen': '',
        Bedrag: '',
        Uitzonderingen: '',
        Regelgeving: '',
        'Websites / Publication URI': '',
        Documenten: '',
        'Bevoegde overheid': 'Lokale overheid',
        'Afleverende dienst': 'Lokale overheid',
        'Adres afleverende dienst': '',
        Type: 'Financieel voordeel',
        Doelgroep: 'Onderneming',
        'Geografische toepassingsgebied': 'Gemeente',
        Thema: 'Economie en Werk',
        "Thema's": 'Economie en Werk',
        'Verwant product': '',
        Labels: '',
        'Geldig van': 'wo, 03/18/2020 - 09:48',
        'Geldig tot': 'ma, 12/31/2035 - 01:00',
      },
      {
        PID: '1846',
        Naam: 'Toelage renovatie of verfraaiing handelspand',
        Titel: 'Toelage renovatie of verfraaiing handelspand',
        Inhoud:
          'Voor de renovatie of verfraaiing van uw handelspand kunt u onder bepaalde voorwaarden in aanmerking komen voor een toelage van uw stad of gemeente.',
        Voorwaarden: '',
        Procedure:
          'Of en hoe u een beroep kunt doen op een lokale toelage kunt u nagaan bij uw stad of gemeente.',
        'Wat meebrengen': '',
        Bedrag: '',
        Uitzonderingen: '',
        Regelgeving: '',
        'Websites / Publication URI': '',
        Documenten: '',
        'Bevoegde overheid': 'Lokale overheid',
        'Afleverende dienst': 'Lokale overheid',
        'Adres afleverende dienst': '',
        Type: 'Financieel voordeel',
        Doelgroep: 'Onderneming',
        'Geografische toepassingsgebied': 'Gemeente',
        Thema: 'Economie en Werk',
        "Thema's": 'Economie en Werk',
        'Verwant product': '',
        Labels: '',
        'Geldig van': 'wo, 03/18/2020 - 09:04',
        'Geldig tot': 'ma, 12/31/2035 - 01:00',
      },
      {
        PID: '1845',
        Naam: 'Toelage leegstaand handelspand',
        Titel: 'Toelage leegstaand handelspand',
        Inhoud:
          'Voor het opwaarderen en heringebruikname van een leegstaand handelspand kunt u onder bepaalde voorwaarden in aanmerking komen voor een of meerdere toelagen van uw stad of gemeente.',
        Voorwaarden: '',
        Procedure:
          'Of en hoe u een beroep kunt doen op lokale toelage kunt u nagaan bij uw stad of gemeente.',
        'Wat meebrengen': '',
        Bedrag: '',
        Uitzonderingen: '',
        Regelgeving: '',
        'Websites / Publication URI': '',
        Documenten: '',
        'Bevoegde overheid': 'Lokale overheid',
        'Afleverende dienst': 'Lokale overheid',
        'Adres afleverende dienst': '',
        Type: 'Financieel voordeel',
        Doelgroep: 'Onderneming',
        'Geografische toepassingsgebied': 'Gemeente',
        Thema: 'Economie en Werk',
        "Thema's": 'Economie en Werk',
        'Verwant product': '',
        Labels: '',
        'Geldig van': 'wo, 03/18/2020 - 09:00',
        'Geldig tot': 'ma, 12/31/2035 - 01:00',
      },
      {
        PID: '1844',
        Naam: 'Lokale toelage bij hinder',
        Titel: 'Lokale toelage bij hinder',
        Inhoud:
          'Naast de hinderpremie van de Vlaamse overheid kan uw onderneming onder bepaalde voorwaarden ook in aanmerking komen voor een toelage van uw stad of gemeente.',
        Voorwaarden: '',
        Procedure:
          'Of en hoe u een beroep kunt doen op lokale toelage kunt u nagaan bij uw stad of gemeente.',
        'Wat meebrengen': '',
        Bedrag: '',
        Uitzonderingen: '',
        Regelgeving: '',
        'Websites / Publication URI': '',
        Documenten: '',
        'Bevoegde overheid': 'Lokale overheid',
        'Afleverende dienst': 'Lokale overheid',
        'Adres afleverende dienst': '',
        Type: 'Financieel voordeel',
        Doelgroep: 'Onderneming',
        'Geografische toepassingsgebied': 'Gemeente',
        Thema: 'Economie en Werk',
        "Thema's": 'Economie en Werk',
        'Verwant product': 'Lokaal hinderattest',
        Labels: '',
        'Geldig van': 'wo, 03/18/2020 - 08:56',
        'Geldig tot': 'ma, 12/31/2035 - 01:00',
      },
      {
        PID: '1854',
        Naam: 'Startersgesprek',
        Titel: 'Startersgesprek',
        Inhoud:
          'Als startende ondernemer kunt u een startersgesprek aanvragen bij uw stad of gemeente. Het startersgesprek maakt u o.a. wegwijs in de wettelijke verplichtingen waaraan u moet voldoen om uw zaak te starten en zorgt ervoor dat u goed geenformeerd aan de slag kunt.',
        Voorwaarden: '',
        Procedure:
          'Of en hoe u een startersgesprek kunt aanvragen kunt u nagaan bij uw stad of gemeente.',
        'Wat meebrengen': '',
        Bedrag: '',
        Uitzonderingen: '',
        Regelgeving: '',
        'Websites / Publication URI': '',
        Documenten: '',
        'Bevoegde overheid': 'Lokale overheid',
        'Afleverende dienst': 'Lokale overheid',
        'Adres afleverende dienst': '',
        Type: 'Advies en begeleiding',
        Doelgroep: 'Onderneming',
        'Geografische toepassingsgebied': 'Gemeente',
        Thema: 'Economie en Werk',
        "Thema's": 'Economie en Werk',
        'Verwant product': '',
        Labels: '',
        'Geldig van': 'wo, 03/18/2020 - 11:19',
        'Geldig tot': 'ma, 12/31/2035 - 01:00',
      },
      {
        PID: '1853',
        Naam: 'Starterscoaching (detailhandel en horeca)',
        Titel: 'Starterscoaching (detailhandel en horeca)',
        Inhoud:
          'Sommige lokale besturen bieden coaching- en ondersteuningstrajecten aan startende ondernemers in detailhandel of horeca.',
        Voorwaarden: '',
        Procedure:
          'Of en hoe u een beroep kunt doen op starterscoaching kunt u nagaan bij uw stad of gemeente.',
        'Wat meebrengen': '',
        Bedrag: '',
        Uitzonderingen: '',
        Regelgeving: '',
        'Websites / Publication URI': '',
        Documenten: '',
        'Bevoegde overheid': 'Lokale overheid',
        'Afleverende dienst': 'Lokale overheid',
        'Adres afleverende dienst': '',
        Type: 'Advies en begeleiding',
        Doelgroep: 'Onderneming',
        'Geografische toepassingsgebied': 'Gemeente',
        Thema: 'Economie en Werk',
        "Thema's": 'Economie en Werk',
        'Verwant product': '',
        Labels: '',
        'Geldig van': 'wo, 03/18/2020 - 10:41',
        'Geldig tot': 'ma, 12/31/2035 - 01:00',
      },
      {
        PID: '1392',
        Naam: 'Belasting op economische bedrijvigheid',
        Titel: 'Belasting op economische bedrijvigheid',
        Inhoud:
          'Alle natuurlijke personen of rechtspersonen die een economische activiteit uitoefenen op het grondgebied van de gemeente zijn onderworpen aan de belasting op economische bedrijvigheid.',
        Voorwaarden:
          'U voert een economische activiteit uit als u voldoet aan een of meer van de volgende voorwaarden: ingeschreven in het handelsregister ingeschreven in het register van de burgerlijke vennootschappen beschikt over een btw-nummer',
        Procedure: 'U dient het aangifteformulier in.',
        'Wat meebrengen': '',
        Bedrag: '',
        Uitzonderingen: '',
        Regelgeving: '',
        'Websites / Publication URI': '',
        Documenten: '',
        'Bevoegde overheid': 'Lokale overheid',
        'Afleverende dienst': 'Lokale overheid',
        'Adres afleverende dienst': '',
        Type: 'Financiele verplichting',
        Doelgroep: 'Onderneming',
        'Geografische toepassingsgebied': 'Gemeente',
        Thema: 'Economie en Werk',
        "Thema's": 'Economie en Werk',
        'Verwant product': '',
        Labels: '',
        'Geldig van': 'vr, 02/05/2016 - 16:09',
        'Geldig tot': 'ma, 12/31/2035 - 01:00',
      },
      {
        PID: '1388',
        Naam: 'Aanvraag tijdelijk parkeerverbod',
        Titel: 'Aanvraag tijdelijk parkeerverbod',
        Inhoud:
          'Wilt u een aantal parkeerplaatsen gebruiken omdat u: verhuist werken uitvoert aan uw woning of handelspand voor langere periode dient te laden en lossen ... Dan kunt u een vergunning aanvragen voor een tijdelijk parkeerverbod. Opgelet: Plaatst u een stelling, container, bouwmaterialen, bouwwerf of vrachtwagen, dan heeft u ook een signalisatievergunning nodig.',
        Voorwaarden:
          'U kunt een tijdelijk parkeerverbod aanvragen op plaatsen waar parkeren is toegestaan.',
        Procedure:
          'U vraagt het tijdelijke parkeerverbod aan met het aanvraagformulier.',
        'Wat meebrengen': '',
        Bedrag: '',
        Uitzonderingen: '',
        Regelgeving: '',
        'Websites / Publication URI': '',
        Documenten: '',
        'Bevoegde overheid': 'Lokale overheid',
        'Afleverende dienst': 'Lokale overheid',
        'Adres afleverende dienst': '',
        Type: 'Toelating',
        Doelgroep: 'Burger, Onderneming, Organisatie',
        'Geografische toepassingsgebied': 'Gemeente',
        Thema: 'Mobiliteit en Openbare Werken',
        "Thema's": 'Mobiliteit en Openbare Werken',
        'Verwant product': 'Signalisatievergunning',
        Labels: '',
        'Geldig van': 'vr, 02/05/2016 - 11:43',
        'Geldig tot': 'ma, 12/31/2035 - 01:00',
      },
      {
        PID: '1015',
        Naam: 'Belasting op vaste reclame zichtbaar van op de openbare weg',
        Titel: 'Belasting op vaste reclame zichtbaar van op de openbare weg',
        Inhoud:
          'Als u vaste reclame plaatst die zichtbaar is voor het publiek van op de openbare weg, moet u hiervoor een belasting betalen.',
        Voorwaarden: '',
        Procedure: '',
        'Wat meebrengen': '',
        Bedrag: '',
        Uitzonderingen: '',
        Regelgeving: '',
        'Websites / Publication URI': '',
        Documenten: '',
        'Bevoegde overheid': 'Lokale overheid',
        'Afleverende dienst': 'Lokale overheid',
        'Adres afleverende dienst': '',
        Type: 'Financiele verplichting',
        Doelgroep: 'Burger, Onderneming, Organisatie',
        'Geografische toepassingsgebied': 'Gemeente',
        Thema: 'Economie en Werk',
        "Thema's": 'Economie en Werk',
        'Verwant product': '',
        Labels: '',
        'Geldig van': 'wo, 09/17/2014 - 14:51',
        'Geldig tot': 'ma, 12/31/2035 - 01:00',
      },
      {
        PID: '1120',
        Naam: 'Subsidie voor het organiseren van lokale economische initiatieven',
        Titel:
          'Subsidie voor het organiseren van lokale economische initiatieven',
        Inhoud:
          'Verenigingen of organisaties die een initiatief organiseren om de lokale economie te promoten of te bevorderen, komen in aanmerking voor een subsidie.',
        Voorwaarden:
          'Om in aanmerking te komen voor de subsidie moet het initiatief: plaatsvinden op het grondgebied van de gemeente gericht zijn op de promotie of bevordering van de lokale economie de individuele belangen van de initiatiefnemer(s) overstijgen gratis toegankelijk zijn voor burgers of klanten.',
        Procedure: '',
        'Wat meebrengen': '',
        Bedrag: '',
        Uitzonderingen: '',
        Regelgeving: '',
        'Websites / Publication URI': '',
        Documenten: '',
        'Bevoegde overheid': 'Lokale overheid',
        'Afleverende dienst': 'Lokale overheid',
        'Adres afleverende dienst': '',
        Type: 'Financieel voordeel',
        Doelgroep: 'Onderneming, Organisatie',
        'Geografische toepassingsgebied': 'Gemeente',
        Thema: 'Economie en Werk',
        "Thema's": 'Economie en Werk',
        'Verwant product': '',
        Labels: '',
        'Geldig van': 'di, 09/30/2014 - 10:32',
        'Geldig tot': 'ma, 12/31/2035 - 01:00',
      },
      {
        PID: '1376',
        Naam: 'Vaste standplaats op de wekelijkse markt',
        Titel: 'Vaste standplaats op de wekelijkse markt',
        Inhoud:
          'De vaste standplaatsen op de wekelijkse markt worden toegewezen per abonnement. Marktkramers die een abonnement wensen op de wekelijkse markt, kunnen hiervoor een aanvraag indienen. Vrije plaatsen worden toegewezen volgens de voorrangsregels opgenomen in het reglement.',
        Voorwaarden:
          'U bent een professionele verkoper of u bent een vertegenwoordiger met productdemonstraties. U bent in het bezit van een machtiging voor ambulante handel (leurkaart).',
        Procedure: 'U dient uw kandidatuur in bij de gemeente.',
        'Wat meebrengen': '',
        Bedrag: '',
        Uitzonderingen: '',
        Regelgeving: '',
        'Websites / Publication URI': '',
        Documenten: '',
        'Bevoegde overheid': 'Federale overheid',
        'Afleverende dienst': 'Lokale overheid',
        'Adres afleverende dienst': '',
        Type: 'Toelating',
        Doelgroep: 'Onderneming',
        'Geografische toepassingsgebied': 'Federaal',
        Thema: 'Economie en Werk',
        "Thema's": 'Economie en Werk',
        'Verwant product': '',
        Labels: '',
        'Geldig van': 'wo, 11/25/2015 - 11:48',
        'Geldig tot': 'ma, 12/31/2035 - 01:00',
      },
      {
        PID: '1122',
        Naam: 'Vergunning voor het laden en lossen',
        Titel: 'Vergunning voor het laden en lossen',
        Inhoud:
          'Om overdag te laden en te lossen in een voetgangersgebied hebt u een vergunning nodig. Deze vergunning geeft u de toelating om: het voetgangersgebied binnen te rijden tot de plaats waar u moet laden of lossen in het voetgangersgebied. U neemt hiervoor altijd de kortste weg vanaf de ingang van het voetgangersgebied tot uw bestemming. stil te staan om te laden en te lossen. De vergunning geeft u geen toelating om: te parkeren binnen het voetgangersgebied door het voetgangersgebied te rijden naar een bestemming buiten het voetgangersgebied',
        Voorwaarden: '',
        Procedure:
          'U moet de vergunning schriftelijk aanvragen aan de hand van het aanvraagformulier. U vult volgende gegevens in: de plaatsen/handelszaken binnen het voetgangersgebied die u moet bezoeken de frequentie van uw bezoeken (dagelijks, wekelijks, maandelijks, andere) de reden waarom u overdag moet laden en lossen een juiste omschrijving van uw activiteit als aanvrager de nummerplaat van het voertuig waarvoor u de vergunning aanvraagt. U kan een jaarvergunning aanvragen of een vergunning voor een beperkte periode.',
        'Wat meebrengen': '',
        Bedrag: '',
        Uitzonderingen: '',
        Regelgeving: '',
        'Websites / Publication URI': '',
        Documenten: '',
        'Bevoegde overheid': 'Lokale overheid',
        'Afleverende dienst': 'Lokale overheid',
        'Adres afleverende dienst': '',
        Type: 'Toelating',
        Doelgroep: 'Onderneming, Organisatie',
        'Geografische toepassingsgebied': 'Gemeente',
        Thema: 'Economie en Werk',
        "Thema's": 'Economie en Werk, Mobiliteit en Openbare Werken',
        'Verwant product': '',
        Labels: '',
        'Geldig van': 'di, 09/30/2014 - 11:19',
        'Geldig tot': 'ma, 12/31/2035 - 01:00',
      },
      {
        PID: '719',
        Naam: 'Vergunning tot het rijden in een voetgangerszone',
        Titel: 'Vergunning tot het rijden in een voetgangerszone',
        Inhoud:
          'Als u in een voetgangerszone woont of u hebt er een bedrijf, dan kunt u een permanente vergunning aanvragen tot het rijden in een voetgangerszone. Als u toegang nodig hebt voor een beperkte periode, dan kunt u een tijdelijke vergunning aanvragen.',
        Voorwaarden: '',
        Procedure: '',
        'Wat meebrengen': '',
        Bedrag: '',
        Uitzonderingen: '',
        Regelgeving: '',
        'Websites / Publication URI': '',
        Documenten: '',
        'Bevoegde overheid': 'Lokale overheid',
        'Afleverende dienst': 'Lokale overheid',
        'Adres afleverende dienst': '',
        Type: 'Toelating',
        Doelgroep: 'Burger, Onderneming',
        'Geografische toepassingsgebied': 'Gemeente',
        Thema: 'Economie en Werk',
        "Thema's": 'Economie en Werk, Mobiliteit en Openbare Werken',
        'Verwant product': '',
        Labels: 'doorgangsvergunning',
        'Geldig van': 'di, 04/30/2013 - 14:59',
        'Geldig tot': 'ma, 12/31/2035 - 01:00',
      },
      {
        PID: '762',
        Naam: 'Gemeentelijke premie voor een startende ondernemer',
        Titel: 'Gemeentelijke premie voor een startende ondernemer',
        Inhoud:
          'Hebt u een onderneming opgestart, dan hebt u recht op een premie voor startende ondernemers.',
        Voorwaarden: '',
        Procedure: '',
        'Wat meebrengen':
          'U brengt het bewijs mee van inschrijving in de kruispuntbank van ondernemingen.',
        Bedrag: '',
        Uitzonderingen: '',
        Regelgeving: '',
        'Websites / Publication URI': '',
        Documenten: '',
        'Bevoegde overheid': 'Lokale overheid',
        'Afleverende dienst': 'Lokale overheid',
        'Adres afleverende dienst': '',
        Type: 'Financieel voordeel',
        Doelgroep: 'Onderneming',
        'Geografische toepassingsgebied': 'Gemeente',
        Thema: 'Economie en Werk',
        "Thema's": 'Economie en Werk',
        'Verwant product': '',
        Labels: '',
        'Geldig van': 'vr, 06/14/2013 - 10:14',
        'Geldig tot': 'ma, 12/31/2035 - 01:00',
      },
      {
        PID: '1961',
        Naam: 'Innovatieve starterssteun',
        Titel: 'Innovatieve starterssteun',
        Inhoud:
          'Innovatieve starterssteun ondersteunt starters in het opnemen van een pioniersrol binnen hun markt. Het gaat om een experimentele oproep die afgesloten wordt op 15 maart 2021.',
        Voorwaarden:
          'Bekijk de voorwaarden om in aanmerking te komen voor innovatieve starterssteun op de website van VLAIO.',
        Procedure:
          'Een starter kan zichzelf niet aanmelden voor deze innovatieve starterssteun. Een aanmelding kan alleen via een van de VLAIO-partners. Lees meer op de website van VLAIO .',
        'Wat meebrengen': '',
        Bedrag: '',
        Uitzonderingen: '',
        Regelgeving: '',
        'Websites / Publication URI':
          'Innovatieve starterssteun (https://www.vlaio.be/nl/subsidies-financiering/innovatieve-starterssteu)',
        Documenten: '',
        'Bevoegde overheid': 'Vlaamse overheid',
        'Afleverende dienst': 'Vlaamse overheid',
        'Adres afleverende dienst': '',
        Type: 'Financieel voordeel',
        Doelgroep: 'Onderneming',
        'Geografische toepassingsgebied': 'Vlaamse Gewest',
        Thema: 'Economie en Werk',
        "Thema's": 'Economie en Werk',
        'Verwant product': '',
        Labels: 'startersteun, starterssteun',
        'Geldig van': 'vr, 03/12/2021 - 11:15',
        'Geldig tot': 'ma, 12/31/2035 - 01:00',
      },
      {
        PID: '1381',
        Naam: 'Aangifte afwijking op de wekelijkse rustdag',
        Titel: 'Aangifte afwijking op de wekelijkse rustdag',
        Inhoud:
          'Elke handelaar of ambachtsman moet verplicht een wekelijkse rustdag hebben. De wekelijkse rustdag is een ononderbroken periode van 24 uur. De rustdag begint automatisch op zondag om 5 uur of om 13 uur en eindigt op de volgende dag op hetzelfde uur. U kunt als handelaar of ambachtsman afwijken van deze sluitingsdag, een aangifte bij de gemeente volstaat hiervoor.',
        Voorwaarden:
          'U sluit uw handelszaak 24 uur ononderbroken. U vermeldt op een duidelijke en van buitenaf zichtbare wijze de wekelijkse rustdag. U houdt de gekozen rustdag minstens 6 maanden aan.',
        Procedure:
          'U kiest uw wekelijkse rustdag en het startuur van de sluiting (5u of 13u) en doet hiervan aangifte bij de gemeente waar uw zaak gevestigd is.',
        'Wat meebrengen': '',
        Bedrag:
          'De aangifte van de afwijking op de wekelijkse rustdag is gratis.',
        Uitzonderingen: '',
        Regelgeving: '',
        'Websites / Publication URI': '',
        Documenten: '',
        'Bevoegde overheid': 'Federale overheid',
        'Afleverende dienst': 'Lokale overheid',
        'Adres afleverende dienst': '',
        Type: 'Toelating',
        Doelgroep: 'Onderneming',
        'Geografische toepassingsgebied': 'Federaal',
        Thema: 'Economie en Werk',
        "Thema's": 'Economie en Werk',
        'Verwant product': 'Aangifte afwijking sluitingstijden',
        Labels: '',
        'Geldig van': 'wo, 12/10/2014 - 12:40',
        'Geldig tot': 'ma, 12/31/2035 - 01:00',
      },
      {
        PID: '1848',
        Naam: 'Aangifte afwijking sluitingstijden',
        Titel: 'Aangifte afwijking sluitingstijden',
        Inhoud:
          'De handelaars moeten zich houden aan de wettelijke sluitingsuren. U kunt als handelaar afwijken van die sluitingstijden. Een aangifte bij de gemeente volstaat. Winkels die gewoon overdag open zijn, moeten volgende sluitingsuren respecteren: voor 5 uur en na 20 uur; voor 5 uur en na 21 uur op vrijdag en de werkdagen die aan een wettelijke feestdag voorafgaan. Als de wettelijke feestdag een maandag is, dan mag de winkel de zaterdag daarvoor tot 21 uur openblijven. Voor de nachtwinkels (nightshops) liggen de sluitingsuren tussen 7 uur en 18 uur, tenzij een gemeentelijk reglement andere sluitingsuren vastlegt.',
        Voorwaarden: '',
        Procedure:
          'Of u kunt afwijken van de sluitingstijden en welke procedure u daarvoor moet volgen kunt u nagaan bij uw stad of gemeente.',
        'Wat meebrengen': '',
        Bedrag: '',
        Uitzonderingen: '',
        Regelgeving: '',
        'Websites / Publication URI': '',
        Documenten: '',
        'Bevoegde overheid': 'Federale overheid',
        'Afleverende dienst': 'Lokale overheid',
        'Adres afleverende dienst': '',
        Type: 'Toelating',
        Doelgroep: 'Onderneming',
        'Geografische toepassingsgebied': 'Federaal',
        Thema: 'Economie en Werk',
        "Thema's": 'Economie en Werk',
        'Verwant product': 'Aangifte afwijking op de wekelijkse rustdag',
        Labels: '',
        'Geldig van': 'wo, 03/18/2020 - 09:39',
        'Geldig tot': 'ma, 12/31/2035 - 01:00',
      },
      {
        PID: '1665',
        Naam: 'Dimona-aangifte',
        Titel: 'Dimona-aangifte',
        Inhoud:
          'De Dimona (Declaration Immediate/Onmiddellijke Aangifte) is het elektronische bericht waarmee de werkgever aan de Rijksdienst voor de Sociale Zekerheid (RSZ) meldt dat een werknemer in dienst komt uit dienst gaat langer of korter werkt dan voorzien. De aangifte is verplicht en gebeurt via de beveiligde onlinedienst Dimona.',
        Voorwaarden:
          'Werknemers De Dimona-aangifte is verplicht voor alle werknemers, inclusief: jobstudenten gelegenheidswerknemers flexi-werknemers en vaste werknemers met doelgroepvermindering in de horeca. Een Dimona-aangifte is niet nodig voor: vrijwilligers sommige stagiairs personen die werken met een PWA-arbeidsovereenkomst gelegenheidswerknemers die aan de slag gaan bij provinciale en plaatselijke besturen. Werkgevers De Dimona is verplicht voor alle werkgevers uit zowel de privesector als de openbare sector.',
        Procedure:
          'Elke werkgever die voor het eerst iemand aanwerft, moet zich als werkgever identificeren bij de RSZ . Met het RSZ-nummer dat hij krijgt, kan hij de onlinediensten van de sociale zekerheid gebruiken. Een werkgever die een RSZ-nummer heeft, kan zich dan registreren en aanmelden op de portaalsite van de sociale zekerheid. Hoe u een Dimona-aangifte doet , leest u in het stappenplan op de website van de sociale zekerheid. Het is belangrijk dat de Dimona-aangiften juist en tijdig uitgevoerd worden . Anders kunnen er problemen ontstaan bij de toekenning van sociale rechten aan werknemers.',
        'Wat meebrengen': '',
        Bedrag: '',
        Uitzonderingen: '',
        Regelgeving: '',
        'Websites / Publication URI':
          'Dimona (https://www.socialsecurity.be/site_nl/employer/applics/dimona/index.htm)',
        Documenten: '',
        'Bevoegde overheid': 'Federale overheid',
        'Afleverende dienst': 'Federale overheid',
        'Adres afleverende dienst': '',
        Type: '',
        Doelgroep: 'Onderneming',
        'Geografische toepassingsgebied': 'Federaal',
        Thema: 'Economie en Werk',
        "Thema's": 'Economie en Werk',
        'Verwant product': '',
        Labels: '',
        'Geldig van': 'vr, 08/17/2018 - 18:45',
        'Geldig tot': 'ma, 12/31/2035 - 01:00',
      },
      {
        PID: '268',
        Naam: 'Subsidiedatabank voor ondernemingen',
        Titel: 'Subsidiedatabank voor ondernemingen',
        Inhoud:
          'In de subsidiedatabank kunt u de belangrijkste steunmaatregelen voor ondernemingen van de provinciale, de Vlaamse, de federale en de Europese overheid opzoeken. U vindt er alle basisinformatie over subsidies, maar ook over andere steunmogelijkheden, zoals financiering en advies.',
        Voorwaarden:
          'Op de website van de subsidiedatabank vindt u ook de brochurereeks Subsidiegidsen voor de ondernemer . Die reeks biedt u per thema een overzicht van de belangrijkste subsidiemaatregelen. Doordat deze brochures automatisch bijgewerkt worden als de informatie in de Subsidiedatabank wordt aangepast, hebt u bij het downloaden altijd de laatste brochures. Blijf op de hoogte via de nieuwsbrief . U kunt zich inschrijven voor de nieuwsbrief Subsidiedatabank . Zo wordt u bij wijzigingen en nieuwe maatregelen via e-mail op de hoogte gebracht.',
        Procedure:
          'Steunmaatregelen opzoeken kunt u: via de alfabetische lijst door het ingeven van een trefwoord in de zoekbalk door met de zoekcriteria een selectie uit te voeren op maat van uw project (hoe beter u uw keuze specificeert, hoe korter de lijst is): steungebied (innovatie, milieu, energiebesparing, ...) type van tegemoetkoming (subsidie, advies, lening, waarborg, ...) leeftijd van de onderneming omvang van de onderneming juridische vorm van de onderneming steunverlenende overheid (Europese, federale, Vlaamse, provinciale overheid). Voor meer advies of begeleiding kunt u contact opnemen met het Agentschap Innoveren en Ondernemen.',
        'Wat meebrengen': '',
        Bedrag: '',
        Uitzonderingen: '',
        Regelgeving: '',
        'Websites / Publication URI':
          'Subsidiedatabank voor ondernemingen (http://www.vlaio.be/subsidiedatabank)',
        Documenten: '',
        'Bevoegde overheid': 'Vlaamse overheid',
        'Afleverende dienst': 'Vlaamse overheid',
        'Adres afleverende dienst':
          'Agentschap Innoveren en Ondernemen\nEllipsgebouw\nKoning Albert II laan 35\n1030 Schaarbeek\n',
        Type: 'Financieel voordeel',
        Doelgroep: 'Onderneming, Organisatie',
        'Geografische toepassingsgebied': 'Vlaamse Gewest',
        Thema: 'Economie en Werk',
        "Thema's": 'Economie en Werk',
        'Verwant product': '',
        Labels:
          'bedrijf, bedrijfssubsidie, bedrijven, databank, ondernemen, ondernemer, onderneming, steun, steunmaatregel, steunmaatregelen, subsidie, subsidiedatabank, subsidies, subsidiewegwijzer, subsidiewijzer, website',
        'Geldig van': 'do, 08/13/2009 - 11:46',
        'Geldig tot': 'ma, 12/31/2035 - 01:00',
      },
      {
        PID: '736',
        Naam: 'Exploitatievergunning voor de horeca',
        Titel: 'Exploitatievergunning voor de horeca',
        Inhoud:
          'Een exploitatievergunning voor de horeca maakt het mogelijk een horeca-zaak open te houden. Elke toekomstige exploitant moet voor het openen, het openhouden of het heropenen van een horeca-zaak een exploitatievergunning hebben. De aanvraag voor de exploitatievergunning gebeurt het best twee maanden voor u uw zaak wilt openen.',
        Voorwaarden: '',
        Procedure: '',
        'Wat meebrengen': '',
        Bedrag: '110 Euro',
        Uitzonderingen:
          'Belastingplichtigen die ondanks de financie?le steunmaatregelen die de Vlaamse en federale overheid aanbieden, zich in financie?le nood bevinden, kunnen beroep doen op de sociale dienst van het lokaal bestuur.',
        Regelgeving:
          'Algemene gemeentebelasting op economische bedrijvigheden 2020-2025, zoals goedgekeurd door de gemeenteraad op 16 december 2019, en gewijzigd in de gemeenteraad van 7 september 2020.\nDe Grondwet, in het bijzonder artikel 170 par. 3 en par. 4.\nHet decreet van 30 mei 2008 betreffende de vestiging, de invordering en de geschillenprocedure van provincie- en gemeentebelastingen.\nDe omzendbrief KB/ABB 2019/2 van 15 februari 2019 betreffende de gemeentefiscaliteit. Retributiereglement fiscale en niet-fiscale ontvangsten, zoals goedgekeurd door de gemeenteraad op 27 mei 2019.',
        'Websites / Publication URI':
          'https://www.sint-martens-latem.be/sites/default/files/atoms/files/gemeentebelasting%20op%20economische%20bedrijvigheden_2020_2025_gecoerdineerde%20versie%202021.pdf',
        Documenten: '',
        'Bevoegde overheid': 'Federale overheid',
        'Afleverende dienst': 'Lokale overheid',
        'Adres afleverende dienst': '',
        Type: 'Toelating',
        Doelgroep: 'Onderneming',
        'Geografische toepassingsgebied': 'Federaal',
        Thema: 'Economie en Werk',
        "Thema's": 'Economie en Werk',
        'Verwant product':
          'Brandveiligheidsattest voor horeca-uitbaters, Geregistreerde-kassasysteem in de horeca',
        Labels: 'exploitatievergunning, horeca',
        'Geldig van': 'di, 05/21/2013 - 00:00',
        'Geldig tot': 'ma, 12/31/2035 - 01:00',
      },
    ],
  };
};
